### ISSUE TITLE
Изучить данные, возвращаемые API почты России

### ISSUE THREAD

**Issue by khudyakovavi** [svetken/post_russia#15]
В вызов Client(....) в примере с сайта добавить аргумент `retxml=True`.
Посмотреть на xml, который приходит в ответе.
Можно вставить его на сайте http://xmlbeautifier.com/ для более наглядного представления.
Определить, какую структуру имеет результат.

**Comment by barsovichok** [comment]
Важные добавления - чтобы API выдавал правильные, нужно добавить retxml=True и перекодирование в utf-8

from suds.client import Client

url = 'https://tracking.russianpost.ru/rtm34?wsdl'
client = Client(url, **retxml=True**, headers={'Content-Type': 'application/soap+xml; charset=utf-8'}, location='https://tracking.russianpost.ru/rtm34/Service.svc')

barcode = 'номер отправления' 
my_login = 'логин от Почты России'
my_password = 'пароль от Почты России'
message = \
"""<?xml version="1.0" encoding="UTF-8"?>
                <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:oper="http://russianpost.org/operationhistory" xmlns:data="http://russianpost.org/operationhistory/data" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Header/>
   <soap:Body>
      <oper:getOperationHistory>
         
         <data:OperationHistoryRequest>
            <data:Barcode>""" + barcode+ """</data:Barcode>
            <data:MessageType>0</data:MessageType>
            
            <data:Language>RUS</data:Language>
         </data:OperationHistoryRequest>
         
         <data:AuthorizationHeader soapenv:mustUnderstand="?">
            <data:login>"""+ my_login +"""</data:login>
            <data:password>""" + my_password + """</data:password>
         </data:AuthorizationHeader>
      </oper:getOperationHistory>
   </soap:Body>
</soap:Envelope>"""

result = client.service.getOperationHistory(__inject={'msg':message})
**result = result.decode('utf-8')**

sFile = open ("otv2.txt",'w')
sFile.write(str(result))
sFile.close()
