### ISSUE TITLE
Изучение redis

### ISSUE THREAD

**Issue by khudyakovavi** [svetken/post_russia#4]
Вкратце о redis
http://www.intuit.ru/studies/courses/3541/783/lecture/29128

Будем использовать его для хранения данных, например, в виде:
Ключ: id:31312313123123123
Значение: история отправления

А также для очереди сообщений для периодических задач (об этом позднее).

Установить для Windows надо попробовать со страницы:
https://github.com/MSOpenTech/redis/releases

**Comment by barsovichok** [comment]
Шпаргалка по Redis https://habrahabr.ru/post/204354/
