### ISSUE TITLE
Добавить файл requirements.txt в проект

### ISSUE THREAD

**Issue by khudyakovavi** [svetken/post_russia#8]
Так как в проекте появляются зависимости, надо создать файл requirements.txt, в котором перечисляются используемые сторонние библиотеки и их версии.
На данный момент используются библиотеки redis и python-telegram-bot, поэтому в файл надо записать 2 строки вида:
```
redis==version
python-telegram-bot==version
```
где version - это номер версии установленной библиотеки.
Узнать, какая версия установлена, можно с помощью команды `pip freeze`, которую нужно выполнить при активированном виртуальном окружении.

После добавления этого файла, можно будет устанавливать все зависимости проекта одной командой:
`pip install -r requirements.txt`

**Comment by barsovichok** [comment]
https://www.dropbox.com/s/smh7il5wt38wzt9/requirements.txt.txt?dl=0

**Comment by khudyakovavi** [comment]
Ага, правильно!)
Теперь надо его создать в папке проекта и закоммитить в репозиторий)
```
git checkout -b requirements_branch
git add requirements.txt
git commit -m "Сообщение"
git push origin requirements_branch
```
